"C" "S" "B" "Z"
"C" "S" "B" "B" "Z"
"C" "S" "B" "B" "B" "Z"
"E" "U" "S" "B" "Z"
"C" "B" "Z"
"C" "S" "B" "  "B" "Z"
"C" "S" "B" "B" "B" "B" "Z"
"E" "U" "S" "B" "B" "Z"
"C" "B" "B" "Z"
"C"  "S" "B" "B" "Z" "B" "Z"

